# Generated by Django 4.0.6 on 2022-07-22 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_and_R', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='end_hour',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='start_hour',
        ),
    ]
