# Generated by Django 4.0.6 on 2022-07-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_and_R', '0002_remove_reservation_end_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avalaibilities',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='avalaibilities',
            name='start',
            field=models.DateField(),
        ),
    ]
