# Generated by Django 4.0.6 on 2022-07-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_and_R', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='calendar',
        ),
        migrations.AddField(
            model_name='reservation',
            name='calendar',
            field=models.ManyToManyField(to='A_and_R.calendar'),
        ),
    ]
