# Generated by Django 4.0.6 on 2022-07-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_and_R', '0005_alter_avalaibilities_end_alter_avalaibilities_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start',
            field=models.DateField(),
        ),
    ]
