# Generated by Django 4.0.6 on 2022-07-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_and_R', '0010_alter_avalaibilities_end_alter_avalaibilities_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avalaibilities',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='avalaibilities',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
