# Generated by Django 4.0.6 on 2022-07-24 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_and_R', '0012_alter_reservation_end_alter_reservation_start'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avalaibilities',
            new_name='Availabilities',
        ),
    ]
